### ISSUE TITLE
source photos of council members

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#10]
@davidmooreppf do you have a good source on some nice open license photos on NYC's 51 council members?

These seem pretty good: http://council.nyc.gov/html/members/members.shtml

**Comment by davidmooreppf** [comment]
I can check with my contact at Council if she has a bulk folder, but I'm guessing that's the best avail. 

I reckon you can scrape those? Otherwise I could download the 51 members and label them according to your preferred ID convention. 

Will ask my staffer on chat now.

**Comment by cathydeng** [comment]
the images at the link above look like the same images on legistar ([example](http://legistar.council.nyc.gov/PersonDetail.aspx?ID=125490&GUID=293B0EB6-EBA8-4AEC-B431-057794CDB3F4&Search=)). the app already loads the legistar image urls for each person ([example](http://legistar.council.nyc.gov/View.ashx?M=P&ID=125490&GUID=293B0EB6-EBA8-4AEC-B431-057794CDB3F4)) & stores it in `headshot` - they just need to be saved as .jpg first, otherwise it's a bunch of gobbledigook

**Comment by derekeder** [comment]
@cathydeng cool if we can get it from legistar, all the better.

let's create a task that pulls down and saves these images.
