### ISSUE TITLE
on dates of stated meetings, run scrapers in morning for event agenda

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#122]
So there's a full council [stated meeting](http://nyc.councilmatic.org/event/433343/) today - I learned the full agenda is only published on Legistar the morning of the meeting. (There's a placeholder document until then that's mostly blank.) 

It's now [here](http://legistar.council.nyc.gov/Calendar.aspx), as Agenda - when you get in, please run a data update manually, if possible, for today? 

And then writing a task in the future would be ideal, if that's feasible. Not huge priority, but will be cool.

**Comment by davidmooreppf** [comment]
Oh ha - I had an old search filter for 2014 set on Legistar, so was looking at an old agenda. That's hilarious.

Looking again, there's a strikethrough that today's meeting has been deferred until tmw, the 29th. So no need to update data today. 

Let's see if the agenda updates tmw morning on Legistar.

**Comment by cathydeng** [comment]
so, the problem here is that when we update the data, we are deleting everything and adding everything, rather than only adding the things that are new (https://github.com/datamade/django-councilmatic/issues/6). this means that content temporarily goes missing on the live site (the update task takes ~20 mins). this is why we are currently updating at an odd hour, 3am or something I think.

the danger with updating the site in the morning is that there will be a 20 minute window where data is incomplete, so we should address https://github.com/datamade/django-councilmatic/issues/6 before we change the schedule for loading data

**Comment by davidmooreppf** [comment]
Cool - I'll ask our contacts at Council if they know the exact time the day's agenda is usually published on Legistar. Depending on when it's posted, whether at 6 or 9am ET or whatever, maybe even late the night before (unlikely though), we can make a determination if it's important to update the site and put up a placeholder for 20m.

**Comment by davidmooreppf** [comment]
Real agenda isn't up yet for 1:30 pm meeting today, so who knows. Will ask Council leg. staff.

**Comment by reginafcompton** [comment]
Closed https://github.com/datamade/django-councilmatic/issues/6...

Running the scraper at 5am UTC and importing data at 11am UTC. Seems okay. Closing!
