### ISSUE TITLE
strip out "stale" tag for now

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#128]
Expected we might get this - feedback is that council work is still ongoing on initiatives tagged Stale, even if the legislation hasn't been active in 60 days. 

Tag text could of course be changed to something, to contrast with Active tag - but Inactive isn't correct, and Dormant / Pending / etc. don't seem accurate. So strip it out for now? 

Clearly it's good to give visitors a sense of the context, but costs outweigh the benefits of the status quo.

**Comment by derekeder** [comment]
I'd be reluctant to strip it out entirely, as it is a very useful indicator as to the status of legislation that 'dies in committee'. 

Is the concern that the 60 day window is too short? Based on some conversations with reporters in Chicago, the window is about 5 months from introduction here.

**Comment by davidmooreppf** [comment]
Yeah I hear that - it's just that offices are still advancing initiatives and feel it's important to their overall work. Let's strip it out for now. 

On the [bill detail](http://nyc.councilmatic.org/legislation/int-854-2015/) page, we could do a bit more to highlight the last date of action in bottom left, for help context.

**Comment by cathydeng** [comment]
@davidmooreppf I changed the cutoff date to 6 months, to add lots more wiggle room. I also think that the stale tag is valuable - it's extremely unlikely that something sitting for over half a year will actually be advancing, & as such it'd be disingenuous to label it as 'active'

is the issue that the count of the stale legislation looks bad, since it's the status with the most bills? if so, I can just remove the count for stale legislation, like we did for council members

**Comment by cathydeng** [comment]
hey @davidmooreppf  - just wanted to check in again. thoughts?

**Comment by davidmooreppf** [comment]
Will respond! Thanks for the ping.
