### ISSUE TITLE
eliminate tabs on NYC items, as with new Chicago design

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#142]
No rush on this. Just as Derek & I chatted over in G-doc, possibility of bringing over new bill page design. See random examples: new Chi [ordinances](http://chicago.councilmatic.org/legislation/o-2016-475/), NYC [intros](http://nyc.councilmatic.org/legislation/int-1046-2016/). 

Questions re: pro's and con's to discuss:  
1. Currently first NYC bill tab is History & Relevant Events. What about bills with lots of actions? Embed & scroll? 
2. What about NYC bills with more than five or so sponsors? Embed & scroll? 
3. Full text embed is fine for NYC though having it on its own page is nice. But probably not worth it if SEO gains overall. 
4. Where will attachments go on NYC? Probably just their own section below text, ha. 
5. Where will comments go, a second tab up top rather than all the way down at bottom? Possibly!

**Comment by cathydeng** [comment]
we got rid of the tabs in councilmatic core, so once we update django-councilmatic on nyc, the tabs will go away automatically and turn into sequential sections
1. default is to show all. we can make it so that it hides anything over N actions, with a button to show more, like this table http://chicago.councilmatic.org/committee/committee-on-budget-and-government-operations/
2. same answer as 1
3. by default it will go on the same page. we can change this tho
4. yup
5. all the way at the bottom I believe, but not sure

**Comment by cathydeng** [comment]
this is resolved now that we've gotten nyc councilmatic on a newer version of django-councilmatic
