### ISSUE TITLE
Search: filtering on committee name not working

### ISSUE THREAD

**Issue by mccc** [datamade/nyc-councilmatic#181]
Because "Committee on Public Safety" is transformed to "%20Public Safety" (with leading space) and not reversed, filtering on e.g. "%20Public Safety" returns zero results:

Related to https://github.com/datamade/django-councilmatic/blob/d30363a80e6efc66b4a797d86cb22f054734a0ce/councilmatic_core/templatetags/extras.py#L80

![screen shot 2016-08-16 at 1 12 40 pm](https://cloud.githubusercontent.com/assets/205007/17710565/6898326e-63b3-11e6-91d1-43324889cc80.png)
![screen shot 2016-08-16 at 1 14 04 pm](https://cloud.githubusercontent.com/assets/205007/17710566/69f6a23a-63b3-11e6-9183-f002603b26e7.png)

**Comment by reginafcompton** [comment]
This is fixed. 

Moved the committee_topic_only filter to search_filter_item.html partial (lines 6 and 13), so that "name" can represent "full_name." 

<img width="944" alt="screen shot 2016-10-27 at 3 16 15 pm" src="https://cloud.githubusercontent.com/assets/13078679/19783696/88a00aae-9c58-11e6-8dab-68f37881e6e0.png">
